/*!
 * The following copyright notice may not be removed under any circumstances.
 * 
 * Copyright:
 * Copyright (C) 2012 by original authors @ fontello.com
 * 
 * Description:
 * Generated by svg2ttf from Fontello project.
 * 
 * Vendor URL:
 * http://fontello.com
 */
Cufon.registerFont({"w":360,"face":{"font-family":"icons","font-weight":400,"font-stretch":"normal","units-per-em":"360","panose-1":"2 0 5 3 0 0 0 0 0 0","ascent":"306","descent":"-54","cap-height":"20","bbox":"-0.875656 -306 360.876 54","underline-thickness":"0","underline-position":"3.6","unicode-range":"U+0041-U+0042"},"glyphs":{" ":{},"A":{"d":"354,-75v13,4,3,31,6,45v0,4,-2,7,-6,7r-277,0v-2,15,8,50,-11,43v-21,-24,-46,-44,-66,-69v18,-27,45,-45,66,-69v4,-4,13,-2,11,5r0,38r277,0xm283,-203v3,-15,-8,-51,11,-43v21,24,48,42,66,69v-19,26,-45,45,-66,69v-4,2,-13,2,-11,-5r0,-39r-277,0v-13,-2,-3,-31,-6,-45v0,-4,2,-6,6,-6r277,0"},"B":{"d":"357,-91v-14,78,-88,145,-177,145v-50,0,-92,-18,-127,-53r-53,53r0,-145r145,0r-58,58v67,75,203,29,220,-58r50,0xm273,-219v-67,-75,-203,-29,-220,58r-49,0v13,-78,87,-145,176,-145v50,0,92,18,127,53r53,-53r0,145r-145,0"},"\u00a0":{}}});
